{% set name = "cmsis-pack-manager" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 94913a3db9695f8d0676a4a74916a5626984e2b46f923ada61881e4f5064079e
  patches:
    - fix_cargo_target_path.patch

build:
  entry_points:
    - pack-manager = cmsis_pack_manager.pack_manager:main
  script:
    - cd rust
    - cargo bundle-licenses --format yaml --output THIRDPARTY.yaml
    - cd ..
    - {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - setuptools >=42
    - setuptools_scm[toml] >=3.4
    - wheel
    - appdirs >=1.4,<2.0
    - milksnake >=0.1.2,<1.0
    - pyyaml >=6.0,<7.0
  run:
    - python
    - appdirs >=1.4,<2.0
    - milksnake >=0.1.2,<1.0
    - pyyaml >=6.0,<7.0

test:
  requires:
    - pip
  commands:
    - pip check
    - pack-manager --help

about:
  home: https://github.com/pyocd/cmsis-pack-manager
  summary: Python manager for CMSIS-Pack index and cache with fast Rust backend
  license: Apache-2.0
  license_file:
    - LICENSE
    - rust/THIRDPARTY.yaml

extra:
  recipe-maintainers:
    - daniel88ferreira
    - rudispr
